# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/VarelaJulio/9d4650b36049083dedce13cc2cc54b96/untitled0.ipynb
"""

numero_inicial = int(input("Ingrese un numero cual sea: "))
sumatoria = 0
for numero in range(numero_inicial):
    sumatoria = sumatoria + (numero + 1)


print("La sumatoria de los numeros desde el numero inicial hasta el numero final es: ",sumatoria)